.TH VIDGROK 1 "2024-02-29"
.SH "NAME"
vidgrok \- Visualize video data captured by a logic analyzer
.SH "SYNOPSIS"
.B vidgrok \fR[\fBOPTIONS\fR]
.SH "DESCRIPTION"
.B vidgrok
is a tool for realtime visualization of data captured by low-cost logic analyzers. Its main intent is to display raw video signals of historic home computers. vidgrok uses libsigrok for capturing and SDL2 for rendering.
.sp
See the project homepage for more documentation:
.sp
https://github.com/stefanschramm/vidgrok/
.SH "OPTIONS"
.B "\-h, \-\-help"
Print usage
.sp
Please use --help to get the complete list of available options.
.SH "LICENSE"
.B vidgrok
is covered by the GNU General Public License (GPL), version 3 or later.
.SH "AUTHORS"
Stefan Schramm <mail@stefanschramm.net>
